# -*- coding: utf-8 -*-
"""Kural_Tabanlı_Sınıflandırma_ile_Potansiyel_Müşteri_Getirisi_Hesaplama.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103OT8RksKS6Wa_DAbeW8wME8efWI9ua4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("persona.csv")
df.head()

source_counts = df['SOURCE'].value_counts()

print(f"\nUnique SOURCE sayısı: {len(source_counts)}")
print("Frekansları:")
print(source_counts)

price_counts = df['PRICE'].value_counts()

price_counts.head()

country_counts = df['COUNTRY'].value_counts()
country_counts.head()

country_totals = df.groupby('COUNTRY')['PRICE'].sum()

country_totals.head()

source_counts = df['SOURCE'].value_counts()

source_counts.head()

country_avg_price = df.groupby('COUNTRY')['PRICE'].mean()

country_avg_price.head()

country_avg_price = df.groupby('SOURCE')['PRICE'].mean()

for country, avg_price in country_avg_price.items():
    print(f"{country}: {avg_price} birim ortalaması")

country_source_avg_price = df.groupby(['COUNTRY', 'SOURCE'])['PRICE'].mean()

country_source_avg_price.head()

grouped_data = df.groupby(['COUNTRY', 'SOURCE', 'SEX', 'AGE'])['PRICE'].mean()

grouped_data.head()

agg_df = grouped_data.reset_index().sort_values(by='PRICE', ascending=False)
agg_df.head()

agg_df = agg_df.rename(columns={'COUNTRY': 'Ulke', 'SOURCE': 'Kaynak', 'SEX': 'Cinsiyet', 'AGE': 'Yas', 'PRICE': 'Ortalama Kazanc'})

# Sonucu ekrana yazdırma
agg_df.head()

agg_df['Age_Category'] = ""
agg_df.loc[agg_df['Yas'] <= 18, 'Age_Category'] = "0-18"
agg_df.loc[(agg_df['Yas'] > 18) & (agg_df['Yas'] <= 35), 'Age_Category'] = "19-35"
agg_df.loc[(agg_df['Yas'] > 35) & (agg_df['Yas'] <= 50), 'Age_Category'] = "36-50"
agg_df.loc[agg_df['Yas'] > 50, 'Age_Category'] = "51+"
agg_df.head()

df2=pd.read_csv('persona.csv')
df2['customers_level_based'] = agg_df['Ulke'] + '_' + agg_df['Kaynak'] + '_' + agg_df['Cinsiyet'] + '_' + agg_df['Age_Category']

# Tekilleştirme işlemi
df2 = df2.groupby('customers_level_based')['PRICE'].mean().reset_index()
df2.head()

df2['SEGMENT'] = pd.cut(df2['PRICE'], bins=4, labels=['A', 'B', 'C', 'D'])
df2.head()

segment_stats = df2.groupby('SEGMENT')['PRICE'].agg(['mean', 'max', 'sum'])
segment_stats.head()

user="tur_android_female_19-35"
user_stats=df2[df2['customers_level_based']==user]
user_stats.head()

user="fra_ios_female_19-35"
user_stats=df2[df2['customers_level_based']==user]
user_stats.head()