# -*- coding: utf-8 -*-
"""pandas_alistirmalar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgTwU1dQyut8lDHsb1iOcEIvXRyZtSnC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)
pd.set_option('display.width',500)
df=sns.load_dataset('titanic')
df.head()

print((df['sex']=="female").value_counts())
print((df['sex']=="male").value_counts())

print(df.iloc[:].nunique())

print(df['class'].nunique())
print(df['parch'].nunique())

print(df['embarked'].dtype)
df['embarked']=df['embarked'].astype('category')
print(df['embarked'].dtype)

print(df['embarked']=='C')
print(df['embarked']!='S')

((df['age']>30) & (df['sex']=='female')).head()

((df['fare']>500) | (df['age']>70)).head()

print(df.isnull().sum())

df.drop('who',axis=1,inplace=True)
df.head()

mod_degeri=df['deck'].mode()[0]
df['deck']=df['deck'].fillna(mod_degeri)

mod_degeri=df['age'].mode()[0]
df['age']=df['age'].fillna(mod_degeri)

grup=df.groupby(['pclass','sex'])['survived'].agg(['mean','sum','count'])
print(grup)

def ageflag(age):
  if age<=30:
    return 1
  else:
    return 0
df['age_flag']=df['age'].apply(lambda x: ageflag(x))

df.head()

df2=sns.load_dataset('tips')
df2.head()

sum_total=df2.groupby('time')['total_bill'].agg(['sum','min','max','mean'])
print(sum_total)

sum_total2=df2.groupby(['day','time'])['total_bill'].agg(['sum','min','max','mean'])
print(sum_total2)

summary_stats = df2[(df2['time'] == 'Lunch') & (df2['sex'] == 'Female')].groupby('day')[['total_bill', 'tip']].agg(['sum', 'min', 'max', 'mean'])

print(summary_stats)

average = df2.loc[(df2['size'] < 3) & (df2['total_bill'] > 10), 'total_bill'].mean()

print(average)

df2['total_bill_tip_sum'] = df2['total_bill'] + df2['tip']
df2.head()

sorted_df = df2.sort_values('total_bill_tip_sum', ascending=False).head(30).reset_index(drop=True)

print(sorted_df)